var cars = ['Ferrari', 'Tesla', 'Benz'];
console.log(cars[0]);
console.log(cars[1]);
console.log(cars[2]);
cars.push('BMW');
console.log(cars[3]);
cars.pop();
var numberOfCars = cars.length;
console.log(numberOfCars);
// cars = cars.sort();
// console.log(cars);
// cars = cars.reverse();
// console.log(cars);
var lastCar = cars[cars.length - 1];
console.log(lastCar);